# Generated by Django 5.1.1 on 2025-07-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_remove_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='product',
            name='producer',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
