services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    restart: always
    networks:
      - dbnet
    expose:
      - 8080
    ports:
      - "80:8088"
    volumes:
      - ./static:/app/www/static
      - ./media:/app/www/media
      - ./logs:/app/www/logs
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - techstore

  techstore:
    build: .
    image: techstore
    container_name: techstore
    restart: always
    command: "gunicorn -c gunicorn.py techstore.wsgi"
    env_file:
      - .env
    links:
      - "postgres:dbps"
    networks:
      - dbnet
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  
  postgres:
    image: postgres:17-alpine
    container_name: psgr
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - dbnet

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    links:
      - "postgres:db"
    networks:
      - dbnet
    depends_on:
      - postgres
  
networks:
  dbnet:
    driver: bridge

volumes:
  postgres-data:

