# Generated by Django 5.1.1 on 2025-08-24 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('requires_delivery', False), models.Q(('delivery_adress__gt', ''), ('delivery_adress__isnull', False)), _connector='OR'), name='requires_delivery_adress_is_not_null'),
        ),
    ]
