# Generated by Django 5.1.1 on 2025-08-24 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='requires_delivery_adress_is_not_null',
        ),
        migrations.AlterField(
            model_name='order',
            name='cash_on_delivery',
            field=models.CharField(choices=[('cash', 'Cash on delivery'), ('card', 'Payment by card')], default='card', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_adress',
            field=models.TextField(blank=True, help_text='Provide a full adress, including your state, city, apartment, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='requires_delivery',
            field=models.CharField(choices=[('required', 'Delivery required'), ('not_required', 'Pickup')], default='required', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('requires_delivery', 'not_required'), models.Q(('delivery_adress__gt', ''), ('delivery_adress__isnull', False)), _connector='OR'), name='requires_delivery_adress_is_not_null'),
        ),
    ]
