# Generated by Django 5.1.1 on 2025-08-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_requires_delivery_adress_is_not_null_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Processing'), ('S', 'Shipped'), ('D', 'Delivered')], default='Processing', max_length=20),
        ),
    ]
