# Generated by Django 5.1.1 on 2025-08-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name="You've bougth this product? Share your opinion about it!"),
        ),
    ]
