# Generated by Django 5.1.1 on 2025-08-24 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-created_timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ('-created_timestamp',)},
        ),
    ]
